version: "3.3"

services:
  influxdb:
    image: influxdb:2.7
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxDb:/var/lib/influxdb2
  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
volumes:
  influxDb: {}
  grafana: {}
